### PR TITLE
feat: enabled smart contract addresses in contract store

### LINKED ISSUE #19: Enable smart contract addresses in contacts store
Right now, [we're checking](https://github.com/stellar/basic-payment-app/blob/ce7defb7a4d3d3d63e4dc74435616180f2040124/src/lib/stores/contactsStore.js#L44-L57) that an entered contact has a valid `G...` address. We should update this `add` function so it can check for and allow contacts with smart contract `C...` addresses.

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
Closes #19 

## Checklist
- [x] Implemented `C...` smart contract checking logic
- [x] Ensured everything works correctly by running `yarn build`

Hi @ElliotFriend, please review and merge this PR under ODHack 8.0!

### CODE REVIEW

**Comment by SoarinSkySagar** [comment]
@ElliotFriend please review the PR for any changes required, closes issue #19

**Review by ElliotFriend — CHANGES_REQUESTED** [review]
Hi, there @SoarinSkySagar!! Thanks for taking on this task!

There have been some updates to packages (#23), which has resulted in some conflicts in your PR. If you get those conflicts resolved, you won't need the import in `package.json`, and you can leave the `StrKey` import alone, as it'll be coming from the updated `@stellar/stellar-sdk` package.

I think your change on line 52 is exactly what we need, though! As soon as you get the new changes merged in and remove the other two changes, I can get this merged right awya.

Thanks!

**Comment by SoarinSkySagar** [comment]
> I think your change on line 52 is exactly what we need, though! As soon as you get the new changes merged in and remove the other two changes, I can get this merged right awya.

@ElliotFriend, conflict resolved!

**Comment by SoarinSkySagar** [comment]
@ElliotFriend can you please review it again? been more than a day since i merged the conflicts

**Review by ElliotFriend — APPROVED** [review]
Great work! Thanks for the contribution!

**Pull request merged**
