### PR TITLE
SEP-24 popup window closes immediately

### LINKED ISSUE #9: SEP-24 popup window closes immediately
When a user clicks the SEP-24 deposit/withdraw buttons on the `/dashboard/transfers` page, the popup displays for a moment, and immediately closes. I suspect the window is picking up a stream of events in the [eventListener part](https://github.com/stellar/basic-payment-app/blob/59e4877d04106cf237a59c0abc6b86cfcec4261f/src/routes/dashboard/transfers/%2Bpage.svelte#L249-L255) now.

We should add some kind of testing logic that only does `popup.close()` in the event that the postMessage says something like "transfer initiated" or "successful" or "aborted" or whatever the status messages might be.

### PR DESCRIPTION
**Pull request by t0fudev**
This is a WIP.

Closes #9.

I added the if statement to check for the events, however I was going to do some testing on checking the different types of status messages and create the if statement properly. 

I got some issues while trying to search the SEP-24 popup window. I went to `dashboard/transfers`, but didn't see the title saying `SEP-24 Transfers` which is only shown once the `stellar.toml` is fetched (I understood this). Also, I'm not seeing any text besides the last paragraph which ends in line 330. 

I would appreciate some guidance on how to show the `SEP-24 Transfers` title to open the popup window, and get the possible messages. After doing my implentation, I would test it properly. Thank you!

### CODE REVIEW

**Comment by ElliotFriend** [comment]
Hi, there @t0fudev!! Thanks for taking on this task!

To see the relevant parts of the interface, follow [the steps here](https://developers.stellar.org/docs/build/apps/example-application-tutorial/manage-trust#user-experience) to add the `testanchor SRT:GCD...Y6B` asset to your account, and then the further information will show up for you to examine.

Let me know if that helps get you going, or if there's any other trouble. Thanks!!

**Comment by t0fudev** [comment]
Hello @ElliotFriend!! Hope you're doing great,

I read the steps and followed them but can't replicate the bug. Also, Í watched closely every action on both buttons but can't see where do the popup close immediately. If you can help me it would be amazing! Thank you.

**Comment by ElliotFriend** [comment]
Hi, @t0fudev! Once you have the asset added (as described in the link I posted above), click the "Transfers" button on the left-side of the screen. That'll take you to where you can authenticate with the anchor, and then you can click a "SEP-24 Deposit" (or something similar) button that will show up. Then, you'll see it open/close immediately.

**Comment by ElliotFriend** [comment]
Hi, @t0fudev!

My guess is you've moved on to other projects for the time-being, or maybe just aren't as interested in implementing this feature as you once were (which is totally fine!). In any case, I'll close the PR, so it doesn't get too stale.

If you _are_ still interested in working on this, we can definitely re-open the PR, and keep moving. Just let me know.

Thanks!

**Pull request closed without merging**
